Textonly issue
Amsterdam/mapserver pull request #346
Opened 2023-01-19 08:25 UTC by emacgillavry

At low zoom levels, only topographic would show up, without the reference map. This pull request fixes this and aligns the drawing order of the Web Mercator map with the drawing order of the RD map.

2023-01-19 09:17 UTC, DonQueso89 commented
is GetCapabilities eruit gehaald zodat de kaart alleen voor generatie gebruikt kan worden?

2023-01-24 08:50 UTC, emacgillavry commented
GetCapabilities is er vooral uitgehaald om `topografie_wm.map` op 1 lijn te brengen met `topografie.map`. De achterliggende gedachte zal inderdaad zijn, dat deze WMS-en alleen voor tile seeding worden gebruikt.

2023-01-27 15:34 UTC, emacgillavry commented
Patch https://github.com/Amsterdam/mapserver/pull/346/commits/16c72798c9e42045cb94964782b677d470796771 loste weliswaar op, dat de kaart ueberhaupt weer beeld liet zien op BGT-niveau, maar door in QGIS een project in Web Mercator juist de `topografie.map` gebruiken of een project in RD juist de `topografie_wm.map` gebruiken zorgde nog steeds voor witte kaarten op sommige zoomniveaus.

De beide MAP-bestanden zijn in eerste instantie opgezet om met hun eigen projectie om te gaan . Daarbij is de belangrijkste use-case altijd het maken van kaarttegels geweest. Omdat we het [tiling-schema van Geonovum](https://www.geonovum.nl/uploads/standards/downloads/nederlandse_richtlijn_tiling_-_versie_1.1.pdf) gebruiken , die is gebaseerd op OGC-standaarden is **91dpi** het uitgangspunt. Dat komt terug in de waarden voor `MAXSCALEDENOMINATOR` en `MINSCALEDENOMINATOR` in de MAP-bestanden voor MapServer en in de waarden voor de resoluties van het tiling grid in MapProxy. Zo wordt bepaald, welke tweede WMS (bijv `bgt.map`, `kbk10.map` of `kbk50.map`) op welk niveau wordt aangeroepen.

QGIS gebruikt voor het tekenen van de kaarten **96 dpi**. Dit gaat meestal goed met het bevragen van de WMS, maar door de herprojectie van Web Mercator naar Rijksdriehoekstel en vice versa zijn de schaalniveaus soms anders. Dus: op basis van het eerste request vanuit QGIS wordt op basis van de `BBOX` in combinatie met de `WIDTH` en `HEIGHT` een schaalniveau bepaald voor `topografie.map` of `topografie_wm.map`. In de eerste WMS wordt op basis van dat schaalniveau bekeken in welke range (tussen `MAXSCALEDENOMINATOR` en `MINSCALEDENOMINATOR` op basis van **91 dpi**) deze valt (`bgt.map`, `kbk10.map` of `kbk50.map`). Vervolgens maakt de eerste WMS een request naar de tweede WMS met dezelfde `WIDTH` en `HEIGHT`, **maar** hierbij wordt de `BBOX` en de `CRS` **veranderd** (zie `wms_srs`). Dit tweede request valt door de andere `BBOX` en `CRS` soms buiten de range die in het request naar de eerste WMS werd bepaald. Dan krijg je dus een wit plaatje terug voor de referentiekaart. Bij `kaartteksten.map` speelt dit niet, omdat daar geen range wordt afgedwongen in `topografie.map` of `topografie_wm.map`.

In https://github.com/Amsterdam/mapserver/pull/346/commits/914d88b625ea3505b5cdd7617b7d9915b0824fad worden in `topografie.map` en `topografie_wm.map` gesteld, dat de tweede WMS (`bgt.map`, `kbk10.map` of `kbk50.map`) zowel Web Mercator als RD ondersteunen. Nadat in het eerste request op basis van de `BBOX` in combinatie met de `WIDTH` en `HEIGHT` een schaalniveau wordt bepaald, wordt in het tweede request **niet alleen dezelfde** `WIDTH` en `HEIGHT` gebruikt, **maar ook dezelfde** `BBOX` en `CRS`! Daarbij **blijft** het schaalniveau tussen het eerste en het tweede request **hetzelfde**. Dan je dus wel een plaatje terug voor de referentiekaart.

2023-02-01 13:19 UTC, DonQueso89 commented
goeie find en dank voor de uitleg.  Voor requests die een dpi anders dan 91 gebruiken betekent dit verder alleen dat er een kleine discrepantie kan zijn tussen wat de server denkt dat het zoomlevel is en wat de client denkt dat het zoomlevel is, waardoor de server misschien eerder of later dan verwacht niets meer terug geeft, toch?

Bijvoorbeeld als een client berekent obv 96 dpi en de server bounds stelt obv 91 dpi dan zou de zoomdenominator voor de server iets kleiner zijn waardoor de kaart iets minder snel wegvalt

2023-02-01 13:21 UTC, DonQueso89 requested changes
er is een meger conflict ontstaan met change s van @roel-devries. kunnen jullie die resolven?

2023-02-09 09:54 UTC, roel-devries commented
@DonQueso89 Edward heeft master gemerged.. Kan de pr door zo denk je? 
Lokaal zie ik geen issues meer met de zoomniveaus in QGIS voor topo +3857 en topo_wm + 289982

2023-02-09 12:04 UTC, DonQueso89 approved these changes

2023-02-09 14:01 UTC, roel-devries commented
@emacgillavry Zou je ook nog kunnen rebasen? Zijn nog wat conflicten helaas

2023-02-28 08:44 UTC, merged